export const GET_ITEMS_SUCCESS = "GET_ITEMS_SUCCESS";
export const GET_ITEMS_FAILURE = "GET_ITEMS_FAILURE";
export const GET_ITEMS_STARTED = "GET_ITEMS_STARTED";

export const GET_MY_ITEMS_SUCCESS = "GET_MY_ITEMS_SUCCESS";
export const GET_MY_ITEMS_FAILURE = "GET_MY_ITEMS_FAILURE";
export const GET_MY_ITEMS_STARTED = "GET_MY_ITEMS_STARTED";

export const GET_ITEM_SUCCESS = "GET_ITEM_SUCCESS";
export const GET_ITEM_FAILURE = "GET_ITEM_FAILURE";
export const GET_ITEM_STARTED = "GET_ITEM_STARTED";

export const GET_ORIGINS_SUCCESS = "GET_ORIGINS_SUCCESS";
export const GET_ORIGINS_FAILURE = "GET_ORIGINS_FAILURE";
export const GET_ORIGINS_STARTED = "GET_ORIGINS_STARTED";

export const CREATE_ITEM_SUCCESS = "CREATE_ITEM_SUCCESS";
export const CREATE_ITEM_FAILURE = "CREATE_ITEM_FAILURE";
export const CREATE_ITEM_STARTED = "CREATE_ITEM_STARTED";

export const ADD_ITEM = "ADD_ITEM";

export const INCREMENT_ITEM = "INCREMENT_ITEM";
export const DECREMENT_ITEM = "DECREMENT_ITEM";
export const REMOVE_ITEM = "REMOVE_ITEM";

export const FILTER_ORIGINS_COUNTRY = 'FILTER_ORIGINS_COUNTRY';

export const START_FILTRED_PRODUCTS = 'START_FILTRED_PRODUCTS';
export const LOAD_FILTRED_PRODUCTS_SUCCESS = 'LOAD_FILTRED_PRODUCTS_SUCCESS';

export const START_MY_FILTRED_PRODUCTS = 'START_MY_FILTRED_PRODUCTS';
export const LOAD_MY_FILTRED_PRODUCTS_SUCCESS = 'LOAD_MY_FILTRED_PRODUCTS_SUCCESS';
export const GET_MY_FILTRED_PRODUCTS_FAILURE = 'GET_MY_FILTRED_PRODUCTS_FAILURE';

export const PATH_ITEM_STARTED = 'PATH_ITEM_STARTED';
export const PATH_ITEM_SUCCESS = 'PATH_ITEM_SUCCESS';
export const PATH_ITEM_FAILURE = 'PATH_ITEM_FAILURE';

export const SET_SELECTED_COUNTRY = 'SET_SELECTED_COUNTRY';
export const SET_MAX_MIN_PRICE = 'SET_MAX_MIN_PRICE'
